#!/bin/bash
load_fetch() {
set -- $(cat /proc/loadavg)
load1=$1
load5=$2
load15=$3
}

get_load_factor() {
case "$load1" in
    \0.*) load_factor=$(( load_factor + 2 )) ;;
    \1.*) load_factor=$(( load_factor + 1 )) ;;
esac
}

load_factor=0
load_fetch
get_load_factor

sleep .2
load_fetch
get_load_factor


if [ ${load_factor} -eq 0 ]; then
	sysctl vm.swappiness=70 2>1 > /dev/null
elif [ ${load_factor} -eq 4 ]; then
	current_swapiness=$( cat /proc/sys/vm/swappiness )
	if [ ${current_swapiness} -lt 96 ]; then
		sysctl vm.swappiness=$(( current_swapiness + 5 )) 2>1 > /dev/null
	fi
else
	sysctl vm.swappiness=80 2>1 > /dev/null
fi

sleep 20
load_factor=0
load_fetch
get_load_factor

sleep .2
load_fetch
get_load_factor


if [ ${load_factor} -eq 0 ]; then
        sysctl vm.swappiness=70 2>1 > /dev/null
elif [ ${load_factor} -eq 4 ]; then
        current_swapiness=$( cat /proc/sys/vm/swappiness )
        if [ ${current_swapiness} -lt 96 ]; then
                sysctl vm.swappiness=$(( current_swapiness + 5 )) 2>1 > /dev/null
        fi
else
	sysctl vm.swappiness=80 2>1 > /dev/null
fi

sleep 20
load_factor=0
load_fetch
get_load_factor

sleep .2
load_fetch
get_load_factor


if [ ${load_factor} -eq 0 ]; then
        sysctl vm.swappiness=70 2>1 > /dev/null
elif [ ${load_factor} -eq 4 ]; then
        current_swapiness=$( cat /proc/sys/vm/swappiness )
        if [ ${current_swapiness} -lt 96 ]; then
                sysctl vm.swappiness=$(( current_swapiness + 5 )) 2>1 > /dev/null
        fi
else
	sysctl vm.swappiness=80 2>1 > /dev/null
fi

