#!/sbin/openrc-run

# Init-Skript for log2ram
# This skript is designed to work on Gentoo Linux with OpenRC

description="Store logfiles in RAM to minimize writes to disk."

depend() {
  need localmount
  before logger
}
  
start() {
  ebegin "Starting Log2Ram"
    /usr/local/bin/log2ram start
  eend $?
}
  
stop() {
  ebegin "Stopping Log2Ram"
    /usr/local/bin/log2ram stop
  eend $?
}

restart() {
  ebegin "Syncing logs to disk"
    /usr/local/bin/log2ram write
  eend $?
}
