#!/bin/bash

. /etc/log2zram.conf

HDD_LOG=/var/hdd.log
ZRAM_LOG=/var/log

LOG_NAME="/usr/local/bin/log2zram/log2zram.log"


isSafe () {
	[ -d $HDD_LOG/ ] || echo "ERROR: $HDD_LOG/ doesn't exist! Can't sync." >> $LOG_NAME
	[ -d $HDD_LOG/ ] || exit 1
}

syncToDisk () {
	isSafe
	rsync -arzh $ZRAM_LOG/ $HDD_LOG/ 2>&1 | tee $LOG_NAME

}

syncFromDisk () {
	isSafe
	getUsage
	LOG_SIZE=$(du -sk $HDD_LOG/ | awk '{ print $1 }')
	if [ "$BYTES_AVAIL" -lt "$LOG_SIZE" ];then
		echo "ERROR: RAM disk too small. Can't sync." >> $LOG_NAME
		umount -l $ZRAM_LOG/
		umount -l $HDD_LOG/
		exit 1
	fi
	rsync -arzh --exclude 'oldlog'  $HDD_LOG/ $ZRAM_LOG/ 2>&1 | tee $LOG_NAME
}

wait_for () {
	while ! grep -qs "$1" /proc/mounts; do
		sleep 0.1
	done
}

createZramLogDrive () {
	# Check Zram Class created
	if [ ! -d "/sys/class/zram-control" ]; then
		modprobe zram
		ZRAM_DEV='0'
	else
		ZRAM_DEV=$(cat /sys/class/zram-control/hot_add)
	fi
	echo ${COMP_ALG} > /sys/block/zram${ZRAM_DEV}/comp_algorithm
	echo ${LOG_DISK_SIZE} > /sys/block/zram${ZRAM_DEV}/disksize
	echo ${SIZE} > /sys/block/zram${ZRAM_DEV}/mem_limit
	mke2fs -t ext4 /dev/zram${ZRAM_DEV}
}

getUsage () {
	BYTES_AVAIL=$(df "/var/log" | tail -1 | awk '{ print $4 }')
	BYTES_USED=$(df "/var/log" | tail -1 | awk '{ print $3 }')
	
}


pruneOldLog() {
	isSafe
	getUsage
	LOG_REMAINING=$(( "( ${BYTES_AVAIL} * 100 ) / ( ${BYTES_AVAIL} + ${BYTES_USED} )" ))
	if [ "$LOG_REMAINING" -lt "$PRUNE_LEVEL" ];then
			rsync -arzh $ZRAM_LOG/oldlog/ $HDD_LOG/oldlog/ 
			rm -rf $ZRAM_LOG/oldlog/* 
	fi
	
}

case "$1" in
	start)
		[ -d $HDD_LOG/ ] || mkdir $HDD_LOG/
		mount --bind $ZRAM_LOG/ $HDD_LOG/
		mount --make-private $HDD_LOG/
		wait_for $HDD_LOG
		createZramLogDrive
		mount -t ext4 -o nosuid,noexec,nodev,user=log2ram /dev/zram${ZRAM_DEV} ${ZRAM_LOG}/
		wait_for $ZRAM_LOG
		syncFromDisk
		;;

	stop)
		syncToDisk
		#ZRAM_LOG=$(awk '$2 == "/var/log" {print $1}' /proc/mounts)
		#ZRAM_LOG=$(echo ${ZRAM_LOG} | grep -o -E '[0-9]+')
		umount -l $ZRAM_LOG/
		umount -l $HDD_LOG/
		# Unsure as even with Root permision denied
		#echo ${ZRAM_LOG} > /sys/class/zram-control/hot_remove
		;;

	write)
		pruneOldLog
		#syncToDisk
		;;

	*)
		echo "Usage: log2ram {start|stop|write}" >&2
		exit 1
	;;
esac
