#!/usr/bin/env bash
set -euo pipefail

systemctl daemon-reload
systemctl enable log2ram.service log2ram-daily.timer

if [ "$1" == "configure" ]; then
	echo "#####         Reboot to activate log2ram         #####"
	echo "##### edit /etc/log2ram.conf to configure options ####"
fi

exit 0
